Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,12 +56,10 @@ jobs:
       - name: Train model with MLflow
         shell: bash
         run: |
-          # Hapus source ~/.bashrc dan gunakan jalur Conda absolut untuk keamanan
-          source /usr/share/miniconda/etc/profile.d/conda.sh 
+          source ~/.bashrc
           conda activate Maintenance-Prediction
-          # Ganti 'mlflow run .' dengan perintah Python langsung
-          python MLProjects/modelling_tuning.py \
-            --data_path MLProjects/Predictive_Maintenance_Preproces.csv
+          cd MLProjects
+          mlflow run . -P data_path=Predictive_Maintenance_Preproces.csv --env-manager=local
 
       # - name: Check model artifact
       #   run: |
@@ -76,13 +74,6 @@ jobs:
           fi
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           echo "RUN_ID=$RUN_ID"
-
-      - name: Export ML model artifact (model only)
-        run: |
-          rm -rf exported_model
-          mkdir -p exported_model
-          # RUN_ID harus didefinisikan di GITHUB_ENV oleh langkah sebelumnya
-          cp -r MLProjects/mlruns/0/$RUN_ID/artifacts/model exported_model/
 
       # - name: Verify model artifact exists
       #   run: |
@@ -101,6 +92,16 @@ jobs:
           conda activate Maintenance-Prediction
           mlflow models build-docker \--model-uri "runs:/$RUN_ID/model" \--name $MODEL_NAME
 
+      - name: Export ML model artifact
+        run: |
+          rm -rf exported_model
+          mkdir -p exported_model
+          cp -r MLProjects/mlruns/0/$RUN_ID/artifacts/models/model exported_model/
+    
+      - name: Debug exported model
+        run: |
+          ls -R exported_model || echo "exported_model NOT FOUND"
+    
       - name: Commit exported ML model artifact to GitHub
         run: |
           git config user.name "github-actions"
